#!/usr/bin/env python3
"""
gen-icon.py — convert a source PNG into both:
  sim/icon_data.h   64x64 RGBA C array, used at runtime by SDL_SetWindowIcon
  sim/sun.ico       Multi-resolution Windows .ico, embedded into sim.exe
                    via the resource file so the taskbar / file explorer
                    show the icon.

Usage:
  python scripts/gen-icon.py [source.png]

Defaults source.png to ../Downloads/img/sun.png if not given.
"""
import sys
import os
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("error: Pillow not installed.  pip install pillow\n")
    sys.exit(1)


def main():
    repo_root = Path(__file__).resolve().parent.parent
    if len(sys.argv) >= 2:
        src = Path(sys.argv[1])
    else:
        src = Path.home() / "Downloads" / "img" / "sun.png"

    if not src.exists():
        sys.stderr.write(f"error: source image not found: {src}\n")
        sys.exit(1)

    img = Image.open(src).convert("RGBA")
    print(f"source: {src} ({img.size[0]}x{img.size[1]} RGBA)")

    # 64x64 RGBA C array for SDL_SetWindowIcon.
    icon64 = img.resize((64, 64), Image.LANCZOS)
    out_h = repo_root / "sim" / "icon_data.h"
    write_c_header(icon64, out_h)
    print(f"wrote   : {out_h}")

    # Multi-resolution Windows .ico for the .rc resource embed.
    sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
    out_ico = repo_root / "sim" / "sun.ico"
    img.save(out_ico, format="ICO", sizes=sizes)
    print(f"wrote   : {out_ico}  (sizes: {sizes})")


def write_c_header(img, path):
    w, h = img.size
    raw = img.tobytes()  # RGBA, row-major, top-to-bottom
    assert len(raw) == w * h * 4

    lines = []
    lines.append(f"/* Auto-generated by scripts/gen-icon.py from sun.png — {w}x{h} RGBA */")
    lines.append(f"#define ICON_WIDTH {w}")
    lines.append(f"#define ICON_HEIGHT {h}")
    lines.append(f"static const unsigned char icon_data[{w}*{h}*4] = {{")
    for y in range(h):
        row_bytes = raw[y * w * 4 : (y + 1) * w * 4]
        line = "  " + ",".join(f"0x{b:02x}" for b in row_bytes) + ","
        lines.append(line)
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
